# Generated by Django 4.2.2 on 2024-08-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_etudiant_email_alter_etudiant_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='classe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('MASCULIN', 'MASCULIN'), ('FEMININ', 'FEMININ')], max_length=50, null=True),
        ),
    ]
